CREATE  TABLE SN_USUARIOS_EXT (

NDOC                                               NUMBER(8),
PASSWORD                                  NOT NULL VARCHAR2(80),
APELLIDO                                  NOT NULL VARCHAR2(25),
NOMBRES                                   NOT NULL VARCHAR2(40),
DOMICILIO                                 NOT NULL VARCHAR2(80),
FECHAVENC                                          DATE,
TEDIRECTO                                          VARCHAR2(15),
TEINTERNO                                          VARCHAR2(6),
CELULAR                                            VARCHAR2(15),
MACADDRESS                                         NUMBER,
EMAIL_PARTICULAR                                   VARCHAR2(50),
EMAIL_CORPORATIVO                                  VARCHAR2(50),
ESTADO                                             NUMBER(2),
NDOC_ADMIN                                         NUMBER(8),
SITIOWEB                                           VARCHAR2(120),
FECHA_AUDIT                                        DATE,
NOMBREDEUSUARIO                           NOT NULL VARCHAR2(50),
USUARIO_ID                                         NUMBER,
EMPRESA                                            VARCHAR2(120),
NOMBRE                                    NOT NULL VARCHAR2(50),
CODIGO                                    NOT NULL VARCHAR2(8) );
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT SN_USUARIOS_EXT USING SELECT * FROM SN_USUARIOS_EXT@USU_PROD;

CREATE TABLE SN_USUARIOS_PNA (

 NOMBREDEUSUARIO                            VARCHAR2(15) NOT NULL,
 PASSWORD                                  VARCHAR2(15) NOT NULL ,
 APELLIDO                                  VARCHAR2(50) NOT NULL ,
 NOMBRES                                   VARCHAR2(50) NOT NULL ,
 DESTINO                                   VARCHAR2(4) NOT NULL ,
 TEDIRECTO                                          VARCHAR2(15),
 TEINTERNO                                          VARCHAR2(6),
 EMAIL                                              VARCHAR2(50),
 FECHAVENC                                          DATE,
 DIRECCION                                          VARCHAR2(50),
 DTO                                                VARCHAR2(50),
 SEC                                                VARCHAR2(50),
 NDOC                                               NUMBER(8),
 NIVACC                                             NUMBER(1),
 ESTADO                                             NUMBER(1),
 NOMBRE                                    VARCHAR2(50) NOT NULL ,
 CODIGO                                    VARCHAR2(8) NOT NULL  );

copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT SN_USUARIOS_PNA USING SELECT * FROM SN_USUARIOS_PNA@USU_PROD;

 
ALTER TABLE RIOS_CANALES_KM DROP COLUMN UNIDAD
ALTER TABLE RIOS_CANALES_KM ADD UNIDAD VARCHAR(50)

ALTER TABLE tbl_zonas DROP COLUMN direccion_postal
ALTER TABLE tbl_zonas ADD direccion_postal VARCHAR(100)

ALTER TABLE tmp_buques DROP COLUMN tipo;
ALTER TABLE tmp_buques ADD tipo VARCHAR(50);

ALTER TABLE TBL_BQ_ESTADOS DROP COLUMN resumen;
ALTER TABLE TBL_BQ_ESTADOS ADD resumen VARCHAR(50);

ALTER TABLE TBL_CAPITAN DISABLE ALL TRIGGERS;
ALTER TABLE INT_USUARIOS DISABLE ALL TRIGGERS;
ALTER TABLE RIOS_CANALES DISABLE ALL TRIGGERS;
ALTER TABLE RIOS_CANALES_KM DISABLE ALL TRIGGERS;
ALTER TABLE TBL_ZONAS DISABLE ALL TRIGGERS;
ALTER TABLE TBL_PUNTODECONTROL DISABLE ALL TRIGGERS;
ALTER TABLE TBL_CONEXIONPUNTODECONTROL DISABLE ALL TRIGGERS;
ALTER TABLE TBL_TIPOEVENTO DISABLE ALL TRIGGERS;
ALTER TABLE TBL_TIPO_CARGA DISABLE ALL TRIGGERS;
ALTER TABLE TBL_REPORTE DISABLE ALL TRIGGERS;
ALTER TABLE TBL_REPORTE_PARAM DISABLE ALL TRIGGERS;
ALTER TABLE TBL_GRUPO DISABLE ALL TRIGGERS;
ALTER TABLE TBL_GRUPOPUNTO DISABLE ALL TRIGGERS;
ALTER TABLE TBL_USUARIOGRUPO DISABLE ALL TRIGGERS;
ALTER TABLE TMP_BUQUES DISABLE ALL TRIGGERS;
ALTER TABLE TBL_ESTADO DISABLE ALL TRIGGERS;
ALTER TABLE TBL_BQ_ESTADOS DISABLE ALL TRIGGERS;
ALTER TABLE PAISES DISABLE ALL TRIGGERS;
ALTER TABLE CODPAIS DISABLE ALL TRIGGERS;
ALTER TABLE TBL_KSTM_PUERTOS DISABLE ALL TRIGGERS;
ALTER TABLE TBL_UNIDAD DISABLE ALL TRIGGERS;
ALTER TABLE TBL_PAISES_CIALA DISABLE ALL TRIGGERS;



copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_CAPITAN USING SELECT * FROM TBL_CAPITAN;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT INT_USUARIOS USING SELECT * FROM INT_USUARIOS;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT RIOS_CANALES USING SELECT * FROM RIOS_CANALES;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT RIOS_CANALES_KM USING SELECT * FROM RIOS_CANALES_KM;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_ZONAS USING SELECT * FROM TBL_ZONAS;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_PUNTODECONTROL USING SELECT * FROM TBL_PUNTODECONTROL;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_CONEXIONPUNTODECONTROL USING SELECT * FROM TBL_CONEXIONPUNTODECONTROL;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_TIPOEVENTO USING SELECT * FROM TBL_TIPOEVENTO;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_TIPO_CARGA USING SELECT * FROM TBL_TIPO_CARGA;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_REPORTE USING SELECT * FROM TBL_REPORTE;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_REPORTE_PARAM USING SELECT * FROM TBL_REPORTE_PARAM;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_GRUPO USING SELECT * FROM TBL_GRUPO;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_GRUPOPUNTO USING SELECT * FROM TBL_GRUPOPUNTO;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_USUARIOGRUPO USING SELECT * FROM TBL_USUARIOGRUPO;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TMP_BUQUES USING SELECT * FROM TMP_BUQUES;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TMP_ESTADO USING SELECT * FROM TMP_ESTADO;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_BQ_ESTADOS USING SELECT * FROM TBL_BQ_ESTADOS;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT PAISES USING SELECT * FROM PAISES;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT CODPAIS USING SELECT * FROM CODPAIS;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_KSTM_PUERTOS USING SELECT * FROM TBL_KSTM_PUERTOS;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_UNIDAD USING SELECT * FROM TBL_UNIDAD;
copy from MBPC/MBPC@192.168.10.120/PRODUCC to SYSTEM/248@127.0.0.1 INSERT TBL_PAISES_CIALA USING SELECT * FROM TBL_PAISES_CIALA;


ALTER TABLE TBL_CAPITAN ENABLE ALL TRIGGERS;
ALTER TABLE INT_USUARIOS ENABLE ALL TRIGGERS;
ALTER TABLE RIOS_CANALES ENABLE ALL TRIGGERS;
ALTER TABLE RIOS_CANALES_KM ENABLE ALL TRIGGERS;
ALTER TABLE TBL_ZONAS ENABLE ALL TRIGGERS;
ALTER TABLE TBL_PUNTODECONTROL ENABLE ALL TRIGGERS;
ALTER TABLE TBL_CONEXIONPUNTODECONTROL ENABLE ALL TRIGGERS;
ALTER TABLE TBL_TIPOEVENTO ENABLE ALL TRIGGERS;
ALTER TABLE TBL_TIPO_CARGA ENABLE ALL TRIGGERS;
ALTER TABLE TBL_REPORTE ENABLE ALL TRIGGERS;
ALTER TABLE TBL_REPORTE_PARAM ENABLE ALL TRIGGERS;
ALTER TABLE TBL_GRUPO ENABLE ALL TRIGGERS;
ALTER TABLE TBL_GRUPOPUNTO ENABLE ALL TRIGGERS;
ALTER TABLE TBL_USUARIOGRUPO ENABLE ALL TRIGGERS;
ALTER TABLE TMP_BUQUES ENABLE ALL TRIGGERS;
ALTER TABLE TBL_ESTADO ENABLE ALL TRIGGERS;
ALTER TABLE TBL_BQ_ESTADOS ENABLE ALL TRIGGERS;
ALTER TABLE PAISES ENABLE ALL TRIGGERS;
ALTER TABLE CODPAIS ENABLE ALL TRIGGERS;
ALTER TABLE TBL_KSTM_PUERTOS ENABLE ALL TRIGGERS;
ALTER TABLE TBL_UNIDAD ENABLE ALL TRIGGERS;
ALTER TABLE TBL_PAISES_CIALA ENABLE ALL TRIGGERS;