CREATE TABLE BUQUES (
ID_BUQUE                 NUMBER(10) NOT NULL,
MATRICULA                VARCHAR2(18) NOT NULL,
NRO_OMI                           NUMBER,
NOMBRE                   VARCHAR2(50) NOT NULL ,
BANDERA                  VARCHAR2(60) NOT NULL ,
ANIO_CONSTRUCCION        NUMBER(5) NOT NULL ,
NRO_ISMM                          NUMBER,
ASTILL_PARTIC                     CHAR(60),
REGISTRO                          CHAR(4),
TIPO_BUQUE               VARCHAR2(80) NOT NULL ,
TIPO_SERVICIO                     CHAR(60),
TIPO_EXPLOTACION                  CHAR(60),
ARBOLADURA                        CHAR(60),
SDIST                             VARCHAR2(8),
VELOCIDAD                         CHAR(8),
ESLORA                            CHAR(10),
MANGA                             CHAR(10),
PUNTAL                            CHAR(10),
ARQUEO_TOTAL                      CHAR(10),
CALADO_MAX                        CHAR(10),
PUERTO_ASIENTO                    CHAR(80),
MATERIAL                          CHAR(50),
SOCIEDADCLASIF                    CHAR(120),
ARQUEO_NETO                       CHAR(10),
DOTACION_MINIMA                   CHAR(20),
TIPO                              CHAR(15)
);