SET PAGES 0
 SET LINES 10000
 SET TRIMSPOOL ON
 SET ECHO OFF
 SET FEEDBACK OFF
 SET VERIFY OFF
 SET HEADSEP OFF
 SET HEADING OFF


 SPOOL C:\TEMP\temp.sql
 SELECT 'COLUMN ' || COLUMN_NAME || ' FORMAT A'||&width
 FROM ALL_TAB_COLUMNS
 WHERE TABLE_NAME = UPPER('&table');
 SPOOL OFF

 @@C:\TEMP\temp.sql

 --host del c:\temp\temp.sql

 SET ECHO ON
 SET VERIFY ON
 SET FEEDBACK ON
 SET TERMOUT ON
 SET HEADSEP ON
 SET HEADING ON
 SET PAGES 25
 SET LINES 60
 SET TRIMSPOOL OFF